teams = {
    'Gujarat Titans': [('WP Saha','wicket_keeper'),
                       ('Shubman Gill','batter'),
                       ('B Sai Sudharsan','batter'),
                       ('HH Pandya','all_rounder'),
                       ('Rashid Khan','bowler'),
                       ('V Shankar','all_rounder'),
                       ('DA Miller','batter'),
                       ('Mohammed Shami','bowler'),
                       ('J Little','bowler'),
                       ('Noor Ahmad','bowler'),
                       ('MM Sharma','bowler'),
                       ('R Tewatia','all_rounder') 
                       ],
    'Chennai Super Kings': [('RD Gaikwad','batter'),
                            ('DP Conway','batter'),
                            ('S Dube','batter'),
                            ('AM Rahane','batter'),
                            ('MS Dhoni','wicket_keeper'),
                            ('RA Jadeja','all_rounder'),
                            ('MM Ali','all_rounder'),
                            ('AT Rayudu','batter'),
                            ('M Theekshana','bowler'), 
                            ('TU Deshpande','bowler'), 
                            ('M Pathirana','bowler'), 
                            ('DL Chahar','bowler'), 
                            ],
    'Punjab Kings':[('NT Ellis','bowler'),
                    ('P Simran Singh','bowler'),
                    ('S Dhawan','batter'),
                    ('Atharva Taide','batter'),
                    ('LS Livingstone','all_rounder'),
                    ('SM Curran','all_rounder'),
                    ('JM Sharma','wicket_keeper'),
                    ('M Shahrukh Khan','batter'),
                    ('Harpreet Brar','all_rounder'),
                    ('RD Chahar','bowler'),
                    ('K Rabada','bowler'),
                    ('Arshdeep Singh','bowler'),
    ],
    'Rajasthan Royals':[('YS Chahal','bowler'),
                    ('D Padikkal','bowler'),
                    ('YBK Jaiswal','batter'),
                    ('JC Buttler','wicket_keeper'),
                    ('NA Saini','bowler'),
                    ('Sandeep Sharma','bowler'),
                    ('SV Samson','wicket_keeper'),
                    ('SO Hetmyer','batter'),
                    ('R Parag','all_rounder'),
                    ('Dhruv Jurel','batter'),
                    ('TA Boult','bowler'),
                    ('A Zampa','bowler'),
    ],
    'Delhi Capitals':[('KK Ahmed','bowler'),
                    ('A Nortje','bowler'),
                    ('PP Shaw','batter'),
                    ('DA Warner','batter'),
                    ('Kuldeep Yadav','bowler'),
                    ('C Sakariya','bowler'),
                    ('PD Salt','wicket_keeper'),
                    ('RR Rossouw','batter'),
                    ('AR Patel','all_rounder'),
                    ('YV Dhull','batter'),
                    ('Aman Hakim Khan','all_rounder'),
                    ('Lalit Yadav','all_rounder'),
    ],
    'Lucknow Super Giants':[('Yash Thakur','bowler'),
                    ('K Gowtham','bowler'),
                    ('Q de Kock','batter'),
                    ('PN Mankad','batter'),
                    ('A Badoni','all_rounder'),
                    ('Sandeep Sharma','bowler'),
                    ('N Pooran','wicket_keeper'),
                    ('Mohsin Khan (2)','bowler'),
                    ('MP Stoinis','all_rounder'),
                    ('KH Pandya','all_rounder'),
                    ('Ravi Bishnoi','bowler'),
                    ('Naveen-ul-Haq','bowler'),
    ],
    'Kolkata Knight Riders':[('Yash Thakur','bowler'),
                    ('Suyash Sharma','bowler'),
                    ('JJ Roy','wicket_keeper'),
                    ('Rahmanullah Gurbaz','batter'),
                    ('VR Iyer','all_rounder'),
                    ('CV Varun','bowler'),
                    ('N Rana','batter'),
                    ('SN Thakur','bowler'),
                    ('AD Russell','all_rounder'),
                    ('RK Singh','batter'),
                    ('VG Arora','bowler'),
                    ('SP Narine','all_rounder'),
    ],
    'Sunrisers Hyderabad':[('Kartik Tyagi','bowler'),
                    ('B Kumar','bowler'),
                    ('MA Agarwal','batter'),
                    ('H Klaasen','batter'),
                    ('Vivrant Sharma','all_rounder'),
                    ('Umran Malik','bowler'),
                    ('AK Markram','batter'),
                    ('HC Brook','batter'),
                    ('Sanvir Singh','all_rounder'),
                    ('GD Phillips','wicket_keeper'),
                    ('Mayank Dagar','bowler'),
                    ('Nithish Kumar Reddy','all_rounder'),
    ],
    'Mumbai Indians':[('K Kartikeya','bowler'),
                    ('JP Behrendorff','bowler'),
                    ('Ishan Kishan','wicket_keeper'),
                    ('RG Sharma','batter'),
                    ('C Green','all_rounder'),
                    ('PP Chawla','bowler'),
                    ('SA Yadav','batter'),
                    ('N Wadhera','batter'),
                    ('Sanvir Singh','all_rounder'),
                    ('TH David','batter'),
                    ('CJ Jordan','bowler'),
                    ('Akash Madhwal','bowler'),
    ],
    'Royal Challengers Bangalore':[('H Sharma','bowler'),
                    ('Mohammed Siraj','bowler'),
                    ('V Kohli','batter'),
                    ('MG Bracewell','all_rounder'),
                    ('GJ Maxwell','all_rounder'),
                    ('WD Parnell','bowler'),
                    ('F du Plessis','batter'),
                    ('Vijaykumar Vyshak','bowler'),
                    ('MK Lomror','all_rounder'),
                    ('KD Karthik','wicket_keeper'),
                    ('Anuj Rawat','batter'),
                    ('HV Patel','bowler'),
    ],
}

# venues = {
#     'venue1': 'Narendra Modi Stadium'
# }